from __future__ import annotations

from typing import Any, List, Optional, Protocol

from pydantic import BaseModel

from app.models.document import Document


class IDocumentRepository(Protocol):
    def get_by_user_id(self, user_id: str) -> List[Document]: ...

    def get_by_id(self, document_id: str, user_id: str) -> Optional[Document]: ...

    def create(self, user_id: str, data: BaseModel) -> Document: ...

    def update(
        self, document_id: str, user_id: str, data: BaseModel
    ) -> Optional[Document]: ...

    def delete(self, document_id: str, user_id: str) -> bool: ...

    def get_by_id_any_user(self, document_id) -> Document | None: ...

    def persist(self, doc: Document) -> Document: ...

    def list_for_user_drive_file_ids(
        self, user_id, drive_file_ids: List[str]
    ) -> List[Document]: ...

    def list_distinct_categories(self, user_id: str) -> List[str]: ...

    def list_expiring_before(self, user_id: str, cutoff: Any) -> List[Document]: ...

    def search_by_user_text(self, user_id: str, query: str) -> List[Document]: ...
